name: Deploy @apps/astro-blog
on:
  push:
    branches: ["main"]
    paths:
      - "apps/astro-blog/**/*"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/astro-blog/**/*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.13.4  

      - name: Install dependencies
        run: pnpm i

      - name: Build Astro
        run: pnpm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: rio
          entrypoint: server/entry.mjs
          root: dist